@baseUrl = http://127.0.0.1:8090/task
###
POST {{baseUrl}}/create HTTP/1.1
Content-Type: application/json
x-wx-openid: "test"
x-wx-unionid: "ttt"
x-wx-appid: "appid"

{
  "feishuTableUrl": "https://8848-top.feishu.cn/wiki/FZb7wjIx7i2UqTkCPmYcKeh1nrd?table=tblNhcDDSCNYOoxe&view=vewxA9jNee",
  "name": "睦辰测试",
  "sql": "select\n  PO.id as orderId,\n  PO.createdAt as createdAt,\n  PO.actuallyPaidFee,\n  TOSI.remainQuantity,\n  TOII.itemName,\n  JSON_UNQUOTE(POVI.venueInfo -> '$.name') as storeName\nfrom PositiveOrder PO\ninner join TradeOrderSkuInfo TOSI on PO.id = TOSI.tradeOrderId and PO.fulfillAt = TOSI.departureDate\ninner join TradeOrderItemInfo TOII on PO.id = TOII.tradeOrderId\ninner join PositiveOrderVenueInfo POVI on PO.id = POVI.orderId\nwhere TOSI.status = 'VALID'\nand PO.createdAt > 1746777251890\nand PO.categoryTwo = 'PARTY_TOUR'\n;",
  "jsScript": "return data.map((item) => {\n    return {\n        \"订单ID\": item.orderId,\n        \"订单创建时间\": item.createdAt,\n        \"订单实付金额\": Number((item.actuallyPaidFee / 100).toFixed(2)),\n        \"订单购买份数\": item.remainQuantity,\n        \"商品名称\": item.itemName,\n        \"门店名称\": item.storeName\n    }\n})",
  "cronExpression": "0 0 * * * *",
  "runMode": "MANUAL",
  "config": { "deleteWholeFeishuTableDataBeforeRun": true },
  "creatorName": "睦辰",
  "updaterName": "睦辰"
}


###
POST {{baseUrl}}/update HTTP/1.1
Content-Type: application/json
x-wx-openid: "test"
x-wx-unionid: "ttt"
x-wx-appid: "appid"

{"id":"68429734ae20db2eef0b5d05","operatorName":"系统用户","attributes":{"name":"睦辰测试","sql":"select 789 as cnt;","jsScript":"return data.map((item) => {\n  return {\n    \"数字\": item.a\n  }\n})","cronExpression":"0 0 20 * * *","feishuTableUrl":"https://8848-top.feishu.cn/wiki/FZb7wjIx7i2UqTkCPmYcKeh1nrd?table=tbltr7bePP15a7fO&view=vewf0uE3Z6"}}

###
POST {{baseUrl}}/change-status HTTP/1.1
Content-Type: application/json
x-wx-openid: "test"
x-wx-unionid: "ttt"
x-wx-appid: "appid"

{
  "id": "683fc0a818ae193d2bc13be0",
  "operatorName": "mc",
  "status": "INACTIVE"
}

###
POST {{baseUrl}}/query HTTP/1.1
Content-Type: application/json
x-wx-openid: "test"
x-wx-unionid: "ttt"
x-wx-appid: "appid"

{
  "name": "test",
  "pageIndex": 0,
  "pageSize": 100
}

###
POST {{baseUrl}}/gen-cron-expression HTTP/1.1
Content-Type: application/json
x-wx-openid: "test"
x-wx-unionid: "ttt"
x-wx-appid: "appid"

{
  "content": "每个月的周三的凌晨3点20分执行"
}

###
POST {{baseUrl}}/get-feishu-table-meta-data HTTP/1.1
Content-Type: application/json
x-wx-openid: "test"
x-wx-unionid: "ttt"
x-wx-appid: "appid"

{
  "url": "https://8848-top.feishu.cn/wiki/ZkPUw9h4OilgUXkjk5lcqL3WnAc?table=tblUtnoGFJOIraIK&view=vewDpHgpmM"
}

###
POST {{baseUrl}}/manual-run HTTP/1.1
Content-Type: application/json
x-wx-openid: "test"
x-wx-unionid: "ttt"
x-wx-appid: "appid"

{
  "taskId": "684694a31fcb90ad4bc8889e",
  "executorName": "MC"
}